version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing AWS SAM CLI and dependencies..."
      - pip install awscli aws-sam-cli

  pre_build:
    commands:
      - echo "Installing Python packages from requirements.txt..."
      - pip install -r requirements.txt -t .

  build:
    commands:
      - echo "Packaging SAM template using bucket: s3-hanas-slproject-serverless-api"
      - sam package \
          --template-file template.yml \
          --output-template-file template-out.yml \
          --s3-bucket s3-hanas-slproject-serverless-api

  post_build:
    commands:
      - echo "Build and packaging complete on $(date)"
      - echo "Generated packaged template: template-out.yml"

artifacts:
  files:
    - template-out.yml
