version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install awscli aws-sam-cli

  build:
    commands:
      - echo "Installing Python dependencies into ./package..."
      - pip install -r requirements.txt -t package
      - echo "Copying lambda_function.py to ./package..."
      - cp lambda_function.py package/
      - echo "Zipping function package..."
      - cd package && zip -r ../function.zip . && cd ..
      - echo "Packaging the SAM template with zipped Lambda..."
      - sam package --template-file template.yml --output-template-file template-out.yml --s3-bucket s3-hanas-slproject-serverless-api

artifacts:
  files:
    - template-out.yml
